[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "unimatch"
version = "0.0.0"
readme = "README.md"
dependencies = [
	"torch",
	"opencv-python",
	"imageio",
	"matplotlib",
]

[tool.setuptools.packages.find]
include = ["unimatch"]
